name: project_setup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2

  # https://pub.dev/packages/dio
  dio: ^5.4.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.1
  # https://pub.dev/packages/envied
  envied: ^0.5.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  # https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.4.9
  # https://pub.dev/packages/flutter_screen_lock
  flutter_screen_lock: ^7.0.4
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^8.1.0
  # https://pub.dev/packages/hive
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  # https://pub.dev/packages/go_router
  go_router: ^5.0.5
  # https://pub.dev/packages/hive
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/internet_connection_checker
  internet_connection_checker: ^1.0.0+1
  # https://pub.dev/packages/intl
  intl: ^0.18.1
  # https://pub.dev/packages/local_auth
  local_auth: ^2.1.7
  # https://pub.dev/packages/logging
  logging: ^1.2.0
  # https://pub.dev/packages/upgrader
  upgrader: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_translation_sheet: ^1.0.32
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .dev.env
    - .qa.env
    - .uat.env
    - .prod.env

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor"
    #ios:
  flavors:
    dev:
      app:
        name: "EcomApp"

      android:
        applicationId: "com.example.project_setup"
        generateDummyAssets: true
        icon: "assets/images/icons/shopping_dev.png"
        #icon: ""
        customConfig:
          applicationIdSuffix: "\".development\""
          versionNameSuffix: "\"Dev\"" # Don't forget to escape strings with \"
          signingConfig: signingConfigs.debug

      ios:
        bundleId: "com.example.project_setup"
        generateDummyAssets: true
        #icon: ""
        #buildSettings:

    qa:
      app:
        name: "EcomApp"

      android:
        applicationId: "com.example.project_setup"
        generateDummyAssets: true
        icon: "assets/images/icons/shopping.png"
        #icon: ""
        customConfig:
          applicationIdSuffix: "\".qa\""
          versionNameSuffix: "\"QA\"" # Don't forget to escape strings with \"
          signingConfig: signingConfigs.qa
      ios:
        bundleId: "com.example.project_setup"
        generateDummyAssets: true
        #icon: ""

    uat:
      app:
        name: "EcomApp"

      android:
        applicationId: "com.example.project_setup"
        generateDummyAssets: true
        icon: "assets/images/icons/shopping.png"
        #icon: ""
        customConfig:
          applicationIdSuffix: "\".uat\""
          versionNameSuffix: "\"UAT\"" # Don't forget to escape strings with \"
          signingConfig: signingConfigs.uat
      ios:
        bundleId: "com.example.project_setup"
        generateDummyAssets: true
        #icon: ""

    prod:
      app:
        name: "EcomApp"

      android:
        applicationId: "com.example.project_setup"
        generateDummyAssets: true
        icon: "assets/images/icons/shopping.png"
        #icon: ""
        customConfig:
          signingConfig: signingConfigs.release
      ios:
        bundleId: "com.example.project_setup"
        generateDummyAssets: true
        #icon: ""
